### ISSUE TITLE
ios 10 incompatible?

### ISSUE THREAD

**Issue by eloirobe** [luc-ass/homebridge-efergy#1]
Hello

I upgrade to ios 10 and now appears in home app that device is incompatible.

**Comment by exkape** [comment]
Hello

i have the same problem, someone have a solution?

**Comment by luc-ass** [comment]
Mine works perfect via the "eve" app. The home app does not support this kind of data.

**Comment by luc-ass** [comment]
could you get it to work?

**Comment by mhellberg** [comment]
Same problem here..

**Comment by luc-ass** [comment]
Again, did you try using "Eve"?
Apples Home-App will report it as not supported because this type of value is custom by Elgato and not standardized within the homekit documentation.

**Comment by mhellberg** [comment]
Yes, Eve is displaying the correct info. But Eve couldnt handle some of my other devices. So thats not an option. But if its an homekit limitation its probably nothing to solve :(

**Comment by luc-ass** [comment]
True. We can probably expect Apple to implement it within this century... ;) After all, this is really relevant Information regarding total consumption. I could imagine my hue bulbes changing color from green to red when energy-usage exceeds a certain value...

**Comment by antgeo** [comment]
Also seeing this accessory is not currently supported by the Home app.

**Comment by bbird81** [comment]
I found another plugin (https://github.com/homespun/homebridge-accessory-neurio), which supports a similar type of device (i.e. energy monitor), that could be (maybe?) a useful inspiration for supporting this plugin directly into the Home app.

If I understood well the code of the Neurio plugin (sorry I'm less than a beginner), it uses hap-nodejs-community-types and the AudioDeviceService UUID (00000001-0000-1000-8000-135D67EC4377) to create a device which can be seen in the Home app.

I don't know what it would look like in the Home app (as I don't have the neurio device), but even if somewhat not perfect, it would be cool to see the house energy consumption directly into the iOS panel.

Hope this helps.

**Comment by sifield** [comment]
Hi, is any further work being done on this?. Does it still work in eve with ios 10?

**Comment by luc-ass** [comment]
This accessory will not change unless Apple decides to add consumption features to its original home app.

This feature is natively supported in eve.
