### ISSUE TITLE
Homekit report "not supported" on my iOS 12.1.2

### ISSUE THREAD

**Issue by Itzamna44** [luc-ass/homebridge-efergy#3]
Hello.
I've installed this plugin but Apple HomeKit report not supported this accessory.
homebridge log look good: Dec 26 10:19:31 homebridge homebridge[3067]: [12/26/2018, 10:19:31 AM] [Efergy] Read Current Consumption: 270 W
Can You help me?

**Comment by luc-ass** [comment]
It is supposed to be like this. Apples Home-App does not support power readings. You should download Elgato Eve
